---
openapi: 3.0.1
info:
  title: h2oa Api (spoofing here 1)
  version: '1.0 (spoofing here 2)'
paths:
  "/path/malformed/by/h2oa":
    post:
      tags:
      - h2oa123_spoofing_here
      parameters:
      - name: h2oa123_spoofing_here
      - description: 123
